Add comments

diff --git a/hack/usr/share/ltsp/ltsp-session b/hack/usr/share/ltsp/ltsp-session
--- a/hack/usr/share/ltsp/ltsp-session
+++ b/hack/usr/share/ltsp/ltsp-session
@@ -37,10 +37,8 @@ test -x $(which daemon) || exit 1
 
 
 #
-# setenv
-# Sets necessary environment variables.
+# Set XAUTHORITY based on current display manager.
 #
-
 setenvxauth() {
     #
     # Use DM's XAUTHORITY
@@ -63,6 +61,10 @@ setenvxauth() {
     logger "ltsp-session: using XAUTHORITY file $XAUTHORITY"
 }
 
+
+#
+# Sets necessary environment variables for LDM scripts.
+#
 setenv() {
     #
     # Load lts.conf
@@ -131,7 +133,8 @@ setenv() {
     #export LDM_SELECTED_SESSION
 
     #
-    # Set X properties by calling appropriate xinitrc.d scripts
+    # Set X properties by calling appropriate xinitrc.d scripts.
+    # Required for LTSPFS.
     #
     if [ -x /usr/share/ltsp/xinitrc ]; then
         /usr/share/ltsp/xinitrc
@@ -139,8 +142,6 @@ setenv() {
 }
 
 
-#
-# waitfor
 #
 # Wait for our socket to appear.
 #
@@ -154,25 +155,20 @@ waitfor () {
 }
 
 
+#
+# Open ssh control socket.
+#
+# The "daemon" utility backgrounds any script or command, and
+# detaches from the controlling terminal.
+# With no controlling terminal, and $DISPLAY set, ssh will use
+# "shm_askpass" specified in SSH_ASKPASS to obtain the password.
+#
 open_socket () {
     S=$1
 
     if [ -n "${DISPLAY}" ]; then
-        #
-        # We have a $DISPLAY variable set.  Spawn an ssh session.
-        # Note, you must install the "daemon" package to obtain the "daemon"
-        # utility.  This nice little program easily backgrounds any script or
-        # command, and has the added advantage (for us) of disassociating from
-        # the controlling terminal.  With no controlling terminal, and $DISPLAY
-        # set, ssh will use the program specified in SSH_ASKPASS to obtain the
-        # passowrd.  Since this was stored in the "auth" phase above,
-        # shm_askpass will pass it to ssh for it to authenticate with.
-        #
         daemon -i -- ssh -q -N -Y -M -K -S "${S}" -l ${PAM_USER_REAL} ${SERVER}
 
-        #
-        # Wait for the socket to actually become available before returning.
-        #
         waitfor "${S}"
 
         logger "ltsp-session: socket $S open"
@@ -180,6 +176,9 @@ open_socket () {
 }
 
 
+#
+# Close ssh control socket.
+#
 close_socket () {
     S=$1
     ssh -q -S "$S" -O exit ${SERVER}
@@ -187,8 +186,7 @@ close_socket () {
 
 
 #
-# This is an example session helper script to be used in conjunction with
-# pam_exec and libpam_sshauth.
+# This is a session helper script to be used in conjunction with pam_exec.
 #
 case ${PAM_TYPE} in
 
@@ -196,6 +194,7 @@ auth)
 
     logger "ltsp-session: start auth"
 
+    # Set XAUTHORITY. Required here for LDM_DIRECTX.
     setenvxauth
 
     #
@@ -211,10 +210,10 @@ auth)
     # POSIX shared memory.
     #
 
-    # This is a hack to work around shm_askpass problem that requires 
-    # that the user defined in PAM_USER exists. By setting it to 
-    # something else (e.g. root or lightdm) while using shm_askpass we 
-    # can work around the problem. A real fix is needed for this. 
+    # This is a hack to work around shm_askpass problem that requires
+    # that the user defined in PAM_USER exists. By setting it to
+    # something else (e.g. root or lightdm) while using shm_askpass we
+    # can work around the problem. A real fix is needed for this.
     # open_socket() is also patched to use PAM_USER_REAL.
     export PAM_USER_REAL="${PAM_USER}"
     export PAM_USER="root"
@@ -236,14 +235,22 @@ auth)
     # when lightdm tries to write .dmrc and .xsession-errors files under
     # it. NFSv4+kerberos and other mount types should also be supported
     # either through explicit mount commands or through automount.
+    logger "ltsp-session: request user data via libnss-sshsock..."
 
     export LDM_HOME=$(getent passwd ${PAM_USER}|awk -F: '{print $6};')
     export PAM_USER_UID=$(getent passwd ${PAM_USER}|awk -F: '{print $3};')
     export PAM_USER_GID=$(getent passwd ${PAM_USER}|awk -F: '{print $4};')
 
+    if [ -z $PAM_USER_UID ]; then
+        logger "ltsp-session: could not get data for user $PAM_USER, aborting"
+        exit 1
+    fi
+    logger "ltsp-session: user $PAM_USER, uid $PAM_USER_UID, gid $PAM_USER_GID"
+
     mkdir -m 0700 -p "${LDM_HOME}"
     chown ${PAM_USER_UID}.${PAM_USER_GID} "${LDM_HOME}"
 
+    logger "ltsp-session: mounting user home directory ($LDM_HOME) with sshfs"
     export SSHFS_HOME=true
     sshfs -o ${follow_home_symlinks}allow_other,ControlPath=${LDM_SOCKET} ${LDM_SERVER}:${LDM_HOME} ${LDM_HOME}
 
@@ -291,8 +298,10 @@ close_session)
 
     #
     # We're closing the session down, so cause the socket to exit.
+    # Libnss-sshsock needs to finalise before closing the socket.
     #
     logger "ltsp-session: close session"
+    sleep 1
     close_socket "${SOCKET}"
 
     ;;
